import './users/users.test';
import './users/points.test';
import './users/collectibles.test';
import './items/items.test';
import './items/collections.test';
import './bits/bits.test';
import './bits/tags.test';
import './discord/role-requests.test';
import './streaks/streaks.test';
